; do NOT edit this file directly!
; copy config.scm.example to config.scm and add your config there

(define-module defaults (export-all))
(select-module defaults)
(use gauche.process)
(define-syntax *get-from-process ; hygienic macro
  (syntax-rules ()
    ((_ args)
     (let* ((process (run-process args :output :pipe))
            (line (read-line (process-output process))))
           (process-wait process)
            line))))

(define gauche-ver "0.9.4")
(define username "")
(define password "")
(define charname "") ; fixme: get charname from char server (based on char-slot)
(define char-slot 0)
(define server "server.themanaworld.org")
(define port 6901)
(define blacklist '())
(define adjective "leafy")
(define emote-limit 1)
(define loop-limit 5)
(define spam-timeout 15)
(define loop-protection #t)
(define version "0.0.8") ; fixme: get the version tag from the current folder
(define build (*get-from-process '(git rev-parse --abbrev-ref HEAD)))
(define source (*get-from-process '(git config --get remote.origin.url)))
