(add-load-path "." :relative)
(use brain)

(define (say foo speaker)
  (print (format "~a says ~a" speaker foo))
  (say-something foo speaker))

(dotimes (30) (print (say "hi tree" "speaker")))
(dotimes (30) (print (say "hello tree" "speaker")))
(dotimes (30) (print (say "heya tree" "speaker")))
(dotimes (30) (print (say "hey tree" "speaker")))
(dotimes (30) (print (say "hi all" "speaker")))
(dotimes (30) (print (say "hello everyone" "speaker")))
(dotimes (30) (print (say "hello all" "speaker")))
(dotimes (30) (print (say "hello everybody" "speaker")))
(dotimes (30) (print (say "hi everyone" "speaker")))
(dotimes (30) (print (say "tell me a joke tree" "speaker")))
(dotimes (30) (print (say "what are you tree" "speaker")))
(dotimes (30) (print (say "kicks tree" "speaker")))
(dotimes (30) (print (say "kick tree" "speaker")))
(dotimes (30) (print (say "shakes tree" "speaker")))
(dotimes (30) (print (say "shake tree" "speaker")))
(dotimes (30) (print (say "pokes tree" "speaker")))
(dotimes (30) (print (say "poke tree" "speaker")))
(dotimes (30) (print (say "die tree" "speaker")))
(dotimes (30) (print (say "waters tree" "speaker")))
(dotimes (30) (print (say "*cuts tree" "speaker")))
(dotimes (10) (print (say "your mmh$ is now open for business" "MMH$")))
(dotimes (30) (print (say "tree" "speaker")))
(dotimes (30) (print (say "CrazyTree" "speaker")))
(dotimes (30) (print (say "hi tree" "Chung")))
(dotimes (30) (print (say "hi tree" "mahouking")))
(dotimes (5) (print (say "nothing" "speaker")))
(dotimes (30) (print (say "shakes tree" "Shainen")))
(dotimes (30) (print (say "shakes tree" "ShaiN2")))
(dotimes (30) (print (say "shake tree" "Silent Dawn")))
(dotimes (30) (print (say "shakes tree" "veryape")))
(dotimes (30) (print (say "burn tree" "veryape")))
(dotimes (10) (print (say "*loves tree*" "speaker")))
(dotimes (3) (print (say "*eats tree*" "speaker")))
(dotimes (3) (print (say "*shoots tree*" "speaker")))
(dotimes (3) (print (say "*plucks tree*" "speaker")))
(dotimes (3) (print (say "*tortures tree*" "speaker")))
(dotimes (3) (print (say "*slaps tree*" "speaker")))
(dotimes (3) (print (say "*poisons tree*" "speaker")))
(dotimes (3) (print (say "*kills tree*" "speaker")))
(dotimes (3) (print (say "*breaks tree*" "speaker")))
(dotimes (3) (print (say "*stabs tree*" "speaker")))
(dotimes (3) (print (say "*throws something at tree*" "speaker")))
(dotimes (5) (print (say "bad tree" "speaker")))
(dotimes (10) (print (say "tree does not recognize this" "speaker")))
(dotimes (10) (print (say "*hates tree*" "speaker")))
(dotimes (1) (print (say "bye tree" "speaker")))
(print (say "how old are you tree" "me"))
(print (say "how chatty are you tree" "me"))

(print (make-face 0))
(print (make-face 2))
(print (make-face 3))
(print (make-face 5))
(print (make-face 7))
(print (make-face 101))
(print (make-face 110))

;;; internal macros, maybe, rarely, likely
(select-module brain)

(define-syntax test-prob
  (syntax-rules ()
    ((_ macro max)
     (let ((count 0))
       (dotimes (max) (if (macro) (inc! count)))
       (print (format "~a => ~a" 'macro (/ (inexact count) max)))))))
(test-prob rarely 1000)
(test-prob maybe 1000)
(test-prob likely 1000)
