(use brain)

(dotimes (30) (print (say-something "hi tree" "speaker")))
(dotimes (30) (print (say-something "hello tree" "speaker")))
(dotimes (30) (print (say-something "heya tree" "speaker")))
(dotimes (30) (print (say-something "hey tree" "speaker")))
(dotimes (30) (print (say-something "hi all" "speaker")))
(dotimes (30) (print (say-something "hello everyone" "speaker")))
(dotimes (30) (print (say-something "hello all" "speaker")))
(dotimes (30) (print (say-something "hello everybody" "speaker")))
(dotimes (30) (print (say-something "hi everyone" "speaker")))
(dotimes (30) (print (say-something "tell me a joke tree" "speaker")))
(dotimes (30) (print (say-something "what are you tree" "speaker")))
(dotimes (30) (print (say-something "kicks tree" "speaker")))
(dotimes (30) (print (say-something "kick tree" "speaker")))
(dotimes (30) (print (say-something "shakes tree" "speaker")))
(dotimes (30) (print (say-something "shake tree" "speaker")))
(dotimes (30) (print (say-something "pokes tree" "speaker")))
(dotimes (30) (print (say-something "poke tree" "speaker")))
(dotimes (30) (print (say-something "die tree" "speaker")))
(dotimes (30) (print (say-something "waters tree" "speaker")))
(dotimes (30) (print (say-something "*cuts tree" "speaker")))
(dotimes (10) (print (say-something "Your MMH$ is now OPEN for Business" "MMH$")))
(dotimes (30) (print (no-idea "tree" "speaker")))
(dotimes (30) (print (no-idea "nothing" "speaker")))
