(use brain)

(define (say foo speaker)
  (print (format "~a says ~a" speaker foo))
  (say-something foo speaker))

(dotimes (30) (print (say "hi tree" "speaker")))
(dotimes (30) (print (say "hello tree" "speaker")))
(dotimes (30) (print (say "heya tree" "speaker")))
(dotimes (30) (print (say "hey tree" "speaker")))
(dotimes (30) (print (say "hi all" "speaker")))
(dotimes (30) (print (say "hello everyone" "speaker")))
(dotimes (30) (print (say "hello all" "speaker")))
(dotimes (30) (print (say "hello everybody" "speaker")))
(dotimes (30) (print (say "hi everyone" "speaker")))
(dotimes (30) (print (say "tell me a joke tree" "speaker")))
(dotimes (30) (print (say "what are you tree" "speaker")))
(dotimes (30) (print (say "kicks tree" "speaker")))
(dotimes (30) (print (say "kick tree" "speaker")))
(dotimes (30) (print (say "shakes tree" "speaker")))
(dotimes (30) (print (say "shake tree" "speaker")))
(dotimes (30) (print (say "pokes tree" "speaker")))
(dotimes (30) (print (say "poke tree" "speaker")))
(dotimes (30) (print (say "die tree" "speaker")))
(dotimes (30) (print (say "waters tree" "speaker")))
(dotimes (30) (print (say "*cuts tree" "speaker")))
(dotimes (10) (print (say "Your MMH$ is now OPEN for Business" "MMH$")))
(dotimes (30) (print (say "tree" "speaker")))
(dotimes (30) (print (say "CrazyTree" "speaker")))
(dotimes (30) (print (say "hi tree" "Chung")))
(dotimes (30) (print (say "hi tree" "mahouking")))
(dotimes (5) (print (say "nothing" "speaker")))
(dotimes (30) (print (say "shakes tree" "Shainen")))
(dotimes (30) (print (say "shakes tree" "ShaiN2")))
(dotimes (30) (print (say "shake tree" "Silent Dawn")))
(dotimes (30) (print (say "shakes tree" "veryape")))
(dotimes (30) (print (say "burn tree" "veryape")))
